site_name: Nuwa
site_description: A Minecraft mod to Create Content Packs
site_author: ZeAmateis
site_url: https://nuwa.readthedocs.io
repo_name: 'jibaymcs/nuwa-mod'
repo_url: 'https://github.com/JibayMcs/Nuwa-Mod'
copyright: 'ZeAmateis - 2019'
google_analytics:
  - 'UA-87583708-2'
  - 'auto'

#Wiki
nav:
  - Welcome !: 'index.md'
  - Bienvenue !: 'index-fr.md'
  - Wut ? (F.A.Q): 'faq.md'
  - 'English Docs':
    - 'Understand Contents Packs':
      - 'Content Pack Files Structure': en/content_pack/#content-pack-files-structure
      - 'Content Pack zip file directory': en/content_pack/#content-pack-zip-file-directory
      - 'Explanations': en/content_pack/#explanations
    - 'Content Pack Creator ?':
      - 'Syntaxes':
          - 'blocks.json':
              - 'Prerequisites': en/syntaxes/blocks/#the-blocksjson-syntax
              - 'Create a Simple Block': en/syntaxes/blocks/#create-a-simple-block
              - 'Create a Complex Block': en/syntaxes/blocks/#create-a-complex-block
              - 'Configurables Objects':
                - 'properties': en/syntaxes/blocks/properties.md
                - 'itemGroup': en/syntaxes/blocks/itemGroup.md
                - 'voxelShape': en/syntaxes/blocks/voxelShape.md
          - 'items.json':
              - 'Prerequisites': en/syntaxes/items/#the-itemsjson-syntax
              - 'Create a Simple Item': en/syntaxes/items/#create-a-simple-item
              - 'Create a Complex Item': en/syntaxes/items/#create-a-complex-item
              - 'Configurables Objects':
                - 'properties': en/syntaxes/items/properties.md
                - 'itemGroup': en/syntaxes/items/itemGroup.md
          - 'itemgroup.json':
              - 'Create your Creative Tab': en/syntaxes/itemgroup.md
      - 'Example - Step by Step' : en/step-by-step.md
    - Developper ?:
      - Work with Nuwa API: en/modder/nuwa_api.md
    - Work with licenses : en/license/license.md
  - Docs Française: https://www.youtube.com/watch?v=dQw4w9WgXcQ
  #  - 'Comprendre les Contents Packs':
      #    - 'Structure des fichiers des Contents Packs': fr/content_pack/#content-pack-files-structure
      #    - 'Dossier des Contents Packs': fr/content_pack/#content-pack-zip-file-directory
      #    - 'Explications': fr/content_pack/#explanations
      #  - 'Créateur de Contents Packs ?':
      #    - 'Syntaxes':
      #        - 'blocks.json':
      #            - 'Prérequis': fr/syntaxes/blocks/#the-blocksjson-syntax
      #            - 'Créer un Bloc Simple': fr/syntaxes/blocks/#create-a-simple-block
      #            - 'Créer un Bloc Complèxe': fr/syntaxes/blocks/#create-a-complex-block
      #            - 'Objets Configurables':
      #              - 'properties': fr/syntaxes/blocks/properties.md
      #             - 'itemGroup': fr/syntaxes/blocks/itemGroup.md
      #              - 'voxelShape': fr/syntaxes/blocks/voxelShape.md
      #       - 'items.json': fr/syntaxes/items.md
      #        - 'itemgroup.json':
      #           - 'Créer votre Onglet Créatif': fr/syntaxes/itemgroup.md
      #    - 'Exemple - Pas à pas' : fr/step-by-step.md
      #   - Developpeur ?:
      #   - Travailler avec l'API MJson: fr/modder/nuwa_api.md
  #   - Travailler avec les licences : fr/license/license.md

# Documentation and theme
theme:
  name: null
  custom_dir: 'material/'
  palette:
    primary: 'green'
    accent: 'light green'
  language: 'en'
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: false
  favicon: 'assets/images/favicon.png'
  static_templates:
    - 404.html

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
      
extra_css:
  - stylesheets/dark_theme.css
  
extra:
  social:
    - type: github
      link: https://github.com/JibayMcs
    - type: 'twitter'
      link: 'https://twitter.com/ZeAmateis'