site_name: MJSon

#Wiki
nav: 
  - Home: 'index.md'
  - Wut ?: 'faq.md'
  - Syntaxes: 'syntaxes.md'
  - Content Pack Creator:
      - 'Your First Pack':
        - 'Content Pack Files Structure': creator/first_pack/#content-pack-files-structure
        - 'Content Pack zip file directory': creator/first_pack/#content-pack-zip-file-directory
        - 'Explanations': creator/first_pack/#explanations
  - Developper ?:
    - Work with MJson API: modder/mjson_api.md

# Documentation and theme
theme:
  name: null
  custom_dir: 'material/'
  palette:
    primary: 'green'
    accent: 'light green'
  language: 'en'
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: false
    
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
      
extra_css:
  - stylesheets/dark_theme.css
  
extra:
  social:
    - type: github
      link: https://github.com/JibayMcs
    - type: 'twitter'
      link: 'https://twitter.com/ZeAmateis'
      
repo_name: 'jibaymcs/mjson-wiki'
repo_url: 'https://github.com/JibayMcs/MJson-Wiki'