site_name: MJSon

#Wiki
nav: 
  - Home: 'index.md'
  - Wut ?: 'faq.md'
  - 'Content Pack':
    - 'Content Pack Files Structure': content_pack/#content-pack-files-structure
    - 'Content Pack zip file directory': content_pack/#content-pack-zip-file-directory
    - 'Explanations': content_pack/#explanations
  - Syntaxes:
      - 'blocks.json': syntaxes/blocks.md
      - 'items.json': syntaxes/items.md
      - 'itemgroup.json': syntaxes/itemgroup.md
  - Developper ?:
    - Work with MJson API: modder/mjson_api.md

# Documentation and theme
theme:
  name: null
  custom_dir: 'material/'
  palette:
    primary: 'green'
    accent: 'light green'
  language: 'en'
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: false
  favicon: 'assets/images/favicon.png'
    
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
      
extra_css:
  - stylesheets/dark_theme.css
  
extra:
  social:
    - type: github
      link: https://github.com/JibayMcs
    - type: 'twitter'
      link: 'https://twitter.com/ZeAmateis'
      
repo_name: 'jibaymcs/mjson-wiki'
repo_url: 'https://github.com/JibayMcs/MJson-Wiki'