site_name: MJSon
site_description: A Minecraft mod to Create Content Packs
site_author: ZeAmateis
site_url: https://mjson.readthedocs.io
repo_name: 'jibaymcs/mjson'
repo_url: 'https://github.com/JibayMcs/MJson'
copyright: 'ZeAmateis - 2019'
google_analytics:
  - 'UA-87583708-2'
  - 'auto'

#Wiki
nav:
  - Home: 'index.md'
  - Wut ? (F.A.Q): 'faq.md'
  - 'Understand Content Pack':
    - 'Content Pack Files Structure': content_pack/#content-pack-files-structure
    - 'Content Pack zip file directory': content_pack/#content-pack-zip-file-directory
    - 'Explanations': content_pack/#explanations
  - 'Content Pack Creator ?':
    - 'Syntaxes':
        - 'blocks.json':
            - 'Prerequisites': syntaxes/blocks/#the-blocksjson-syntax
            - 'Create a Simple Block': syntaxes/blocks/#create-a-simple-block
            - 'Create a Complex Block': syntaxes/blocks/#create-a-complex-block
            - 'Configurables Objects':
              - 'properties': syntaxes/blocks/properties.md
              - 'itemGroup': syntaxes/blocks/itemGroup.md
              - 'voxelShape': syntaxes/blocks/voxelShape.md
        - 'items.json': syntaxes/items.md
        - 'itemgroup.json':
            - 'Create your Creative Tab': syntaxes/itemgroup.md
    - 'Example - Step by Step' : step-by-step.md
  - Developper ?:
    - Work with MJson API: modder/mjson_api.md
  - Work with licenses : license/license.md

# Documentation and theme
theme:
  name: null
  custom_dir: 'material/'
  palette:
    primary: 'green'
    accent: 'light green'
  language: 'en'
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "\uE80C"
  feature:
    tabs: false
  favicon: 'assets/images/favicon.png'
  static_templates:
    - 404.html

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
      
extra_css:
  - stylesheets/dark_theme.css
  
extra:
  social:
    - type: github
      link: https://github.com/JibayMcs
    - type: 'twitter'
      link: 'https://twitter.com/ZeAmateis'